// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6JSOoB-hZ-3xhyIfjcvKugXbTK4RA6vY',
    appId: '1:930010419385:web:e579eeb887a2085c2e0b68',
    messagingSenderId: '930010419385',
    projectId: 'nota-application',
    authDomain: 'nota-application.firebaseapp.com',
    storageBucket: 'nota-application.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhjGPNp78LAqZWuKeWPr-Rgd2eWmyFtVg',
    appId: '1:930010419385:android:39c9cc8aee4916632e0b68',
    messagingSenderId: '930010419385',
    projectId: 'nota-application',
    storageBucket: 'nota-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx7_0lrw6otV2K_ObXMhD1Kr7HBdr34UE',
    appId: '1:930010419385:ios:cb481d90972cf7a72e0b68',
    messagingSenderId: '930010419385',
    projectId: 'nota-application',
    storageBucket: 'nota-application.firebasestorage.app',
    iosBundleId: 'com.example.nota',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx7_0lrw6otV2K_ObXMhD1Kr7HBdr34UE',
    appId: '1:930010419385:ios:cb481d90972cf7a72e0b68',
    messagingSenderId: '930010419385',
    projectId: 'nota-application',
    storageBucket: 'nota-application.firebasestorage.app',
    iosBundleId: 'com.example.nota',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6JSOoB-hZ-3xhyIfjcvKugXbTK4RA6vY',
    appId: '1:930010419385:web:9ccb7b7036de0b412e0b68',
    messagingSenderId: '930010419385',
    projectId: 'nota-application',
    authDomain: 'nota-application.firebaseapp.com',
    storageBucket: 'nota-application.firebasestorage.app',
  );
}
