// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBEaI-E5CGiU0KHvMANN8fSVUiU_LQmGs',
    appId: '1:248733349649:web:b6d5f9816d95d72091beb0',
    messagingSenderId: '248733349649',
    projectId: 'fleeds',
    authDomain: 'fleeds.firebaseapp.com',
    storageBucket: 'fleeds.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJlKSPSmATfuyAvLNO6cBfDMd_SDENvBs',
    appId: '1:919733218239:android:a83812585fa2b311da8f0a',
    messagingSenderId: '919733218239',
    projectId: 'fleeds',
    storageBucket: 'fleeds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWMUotSmAY6aW_UlrNRDxZLo5tB51Y0bA',
    appId: '1:919733218239:ios:9afd0098582beb53da8f0a',
    messagingSenderId: '919733218239',
    projectId: 'fleeds',
    storageBucket: 'fleeds.firebasestorage.app',
    iosBundleId: 'com.example.fleeds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWMUotSmAY6aW_UlrNRDxZLo5tB51Y0bA',
    appId: '1:919733218239:ios:9afd0098582beb53da8f0a',
    messagingSenderId: '919733218239',
    projectId: 'fleeds',
    storageBucket: 'fleeds.firebasestorage.app',
    iosBundleId: 'com.example.fleeds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp9vjqRXxsy_E6jsPqXaTD55VpBZuL2iY',
    appId: '1:919733218239:web:1aaa6bfa0f0222feda8f0a',
    messagingSenderId: '919733218239',
    projectId: 'fleeds',
    authDomain: 'fleeds.firebaseapp.com',
    storageBucket: 'fleeds.firebasestorage.app',
  );

}
